### ISSUE TITLE
Unable to get Vuzix M100 SDK to work on Android Studio for this code to work. Camera blank.

### ISSUE THREAD

**Issue by axilaris** [vuzixtokyo/sample-barcode-scanner#1]
I am unable to integrate Vuzix M100 sdk to get this code working.

error output: "Failed to find target Vuzix Corporation: Vuzix M100 Add-On:15"

Here is a screenshot of the issue: https://imgur.com/a/84JLZW4

based on this vuzix documentation:
http://files.vuzix.com/Content/Upload/Driver_File_m100sdk_manual_jpn_20151226175838467.pdf
android vuzix sdk link may not be working (section 1.1.1). Is there an update for this ?
* http://vuzix.com/k79g75yXoS/addon.xml
we tried also with https but it didnt work https://vuzix.com/[secret]/addon.xml

it works on android device but not on vuzix eyeglasses (its blank screen but we are able to see the scan line overlay)

**Comment by keiji** [comment]
Hi, please try `https://www.vuzix.com/...`

**Comment by axilaris** [comment]
Hi Keiji, we have tried https://vuzix.com/k79g75yXoS/addon.xml, its the same result

**Comment by axilaris** [comment]
does it work for you ?

**Comment by keiji** [comment]
Hi @axilaris, would you append `www.` before `vuzix.com`.

`https://www.vuzix.com/k79g75yXoS/addon.xml`

Above url work for me.

FYI, the server(vuzix.com) returns that http status code `303 See other` with `Location: https://www.vuzix.com/k79g75yXoS/addon.xml`. However, Android Studio doesn't accept it.

**Comment by axilaris** [comment]
ok will try with https://www.vuzix.com/k79g75yXoS/addon.xml, will update soon. thank you

**Comment by axilaris** [comment]
it works now with the compilation. however there is still some errors. we are investigating.

Error:Unsupported method: BaseConfig.getApplicationIdSuffix().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

**Comment by keiji** [comment]
I suppose to you are using Android Studio 3.x.
This sample project is for 2.x.

You have to make update some setting files(3d16b57c12940dcbc409e70dceb2d02f798ba6f9).

**Comment by axilaris** [comment]
compilation its working. we just fix the gradle version as in (first answer)
https://stackoverflow.com/questions/44546849/unsupported-method-baseconfig-getapplicationidsuffix

however the app is now quite working, I will open another issue. This issue can consider close.
