### ISSUE TITLE
barcode scanner app cannot read barcode, is there any specific configurations ?

### ISSUE THREAD

**Issue by axilaris** [vuzixtokyo/sample-barcode-scanner#3]
After solving the compilation issue
https://github.com/vuzixtokyo/sample-barcode-scanner/issues/1

We are able to install the app into Vuzix M100. However, its just a plain camera but upside down.

Is it suppose to scan barcode ? Doesnt seem to be working. How do I enable barcode scanning ?

Even on an android phone, the orientation is changed, but I guess this is to adapt to Vuzix M100. However, on the phone its also not able to detect the barcode. Here is how it looks like: https://imgur.com/a/6O10O7z

Any idea how to get this app to read barcode ? Any specific configurations ?

**Comment by keiji** [comment]
Hi,

I suppose to you're using M100 Revision B. This project was developed for M100 Revision A( old hardware).

You can set camera preview orientation via Camera API.
https://developer.android.com/training/camera/cameradirect#TaskOrientation

Thanks.

**Comment by axilaris** [comment]
Thanks. we somehow got it working. just made some modification on the barcode decoding. https://gitlab.com/firdausmah/barcodescanner_for_vuzix_m100

Thanks a lot Keiji-san
